# Generated by Django 3.0.3 on 2020-02-13 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100)),
                ('subproject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stream_from', to='project.SubProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Okr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100)),
                ('stream', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='okr_from', to='project.Stream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
