# Generated by Django 3.0.3 on 2020-02-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_assignment_okr'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teammember',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assignment_from', to='project.TeamMember'),
        ),
    ]
